// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanHang.Models;

namespace WebBanHang.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240528023134_dulieumoi")]
    partial class dulieumoi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebBanHang.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Áo Thun"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Áo Khoác"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Áo sơ mi"
                        },
                         new
                         {
                             Id = 4,
                             DisplayOrder = 4,
                             Name = "Quần Jean"
                         },
                          new
                          {
                              Id = 5,
                              DisplayOrder = 5,
                              Name = "Quần Short"

                          });

                });

            modelBuilder.Entity("WebBanHang.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                          new
                          {
                              Id = 1,
                              CategoryId = 1,
                              Name = "Áo thun cổ tim",
                              Price = 300.0,

                          },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Áo thun cổ tròn",
                            Price = 350.0,

                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Áo thun cổ chữ V",
                            Price = 400.0,

                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "Áo Thun Cổ Trụ",
                            Price = 420.0,

                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Name = "Áo Thun Cổ Hàn Quốc",
                            Price = 630.0,

                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Name = "Áo Khoác Bomber",
                            Price = 750.0,

                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Name = "Áo Khoác Lông",
                            Price = 820.0,

                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Name = "Áo Khoác Phao",
                            Price = 950.0,

                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Name = "Áo Khoác Phối Mũ",
                            Price = 1200.0,

                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Name = "Áo Khoác Cardigan",
                            Price = 1450.0,

                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Name = "Quần Jeans Basics",
                            Price = 750.0,

                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Name = "Quần ống loe",
                            Price = 1250.0,

                        },
                         new
                         {
                             Id = 13,
                             CategoryId = 2,
                             Name = "Quần Jeans Rách gối",
                             Price = 1250.0,

                         },
                          new
                          {
                              Id = 14,
                              CategoryId = 2,
                              Name = "Quần ống rộng",
                              Price = 1250.0,

                          },
                           new
                           {
                               Id = 15,
                               CategoryId = 2,
                               Name = "Quần ống đứng ",
                               Price = 1250.0,

                           },
                            new
                            {
                                Id = 16,
                                CategoryId = 2,
                                Name = "Quần Short kaki",
                                Price = 1250.0,

                            },
                             new
                             {
                                 Id = 17,
                                 CategoryId = 2,
                                 Name = "Quần short ống rộng",
                                 Price = 1250.0,

                             },
                              new
                              {
                                  Id = 18,
                                  CategoryId = 2,
                                  Name = "Quần short nam vải tây",
                                  Price = 1250.0,

                              },
                               new
                               {
                                   Id = 19,
                                   CategoryId = 2,
                                   Name = "Quần short thun",
                                   Price = 1250.0,

                               },
                                new
                                {
                                    Id = 20,
                                    CategoryId = 2,
                                    Name = "Quần short đi biển",
                                    Price = 1250.0,


                                });
                });

            modelBuilder.Entity("WebBanHang.Models.Product", b =>
                {
                    b.HasOne("WebBanHang.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
